apiVersion: apps/v1
kind: Deployment
metadata:
  name: portfolio-yhb
  labels:
    app: portfolio-yhb
spec:
  replicas: 2
  selector:
    matchLabels:
      app: portfolio-yhb
  template:
    metadata:
      labels:
        app: portfolio-yhb
    spec:
      containers:
      - name: portfolio-yhb
        image: IMAGE_PLACEHOLDER
        ports:
        - containerPort: 30001
---
apiVersion: v1
kind: Service
metadata:
  name: portfolio-yhb-service
spec:
  type: NodePort
  selector:
    app: portfolio-yhb
  ports:
  - port: 30001
    targetPort: 30001
    nodePort: 30001